[package]
name = "mirnet-server"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "3"
anyhow = "1.0"
image = "0.23.14"
structopt = "0.3"
tensorflow = { version = "0.17.0", features = ["tensorflow_gpu"] }
thiserror = "1.0"